## build environment

FROM node:12.2.0-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY /app/package*.json /app/

# TODO: use APP_ENV to determine which environment to build for

# local
RUN npm install --verbose
RUN npm install @vue/cli@3.11.0 -g --verbose

# prod
# RUN npm install --production --verbose
# RUN npm install @vue/cli@3.11.0 -g --verbose

COPY /app /app
RUN npm run build


## production environment

FROM nginx:1.16.0-alpine

COPY --from=build /app/dist /usr/share/nginx/html

# RUN rm /etc/nginx/conf.d/default.conf
COPY /docker/nginx/default.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# https://mherman.org/blog/dockerizing-a-vue-app/#production